name: english_words
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5

  flutter_bloc: ^8.1.2

  get_it: ^7.2.0
  injectable: ^2.1.0

  auto_route: ^5.0.4

  freezed_annotation: ^2.2.0

  json_annotation: ^4.8.0

  flutter_svg: ^2.0.4

  http: ^0.13.5
  html: ^0.15.2

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3

  flutter_lints: ^2.0.1

  flutter_launcher_icons: ^0.12.0

  injectable_generator: ^2.1.4

  auto_route_generator: ^5.0.3

  flutter_gen_runner: ^5.2.0

  freezed: ^2.3.2

  json_serializable: ^6.6.1

flutter:

  generate: true

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato_regular.ttf
          style: normal
          weight: 400
        - asset: fonts/lato_bold.ttf
          style: normal
          weight: 700
    - family: FiraSans
      fonts:
        - asset: fonts/fira_sans_italic.ttf
          style: italic
          weight: 400

flutter_gen:
  integrations:
    flutter_svg: true