name: english_words
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <=3.1.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1

  flutter_bloc: ^8.1.3

  get_it: ^7.6.2
  injectable: ^2.3.0

  auto_route: ^7.8.3

  freezed_annotation: ^2.2.0

  json_annotation: ^4.8.1

  flutter_svg: ^2.0.7

  http: ^1.1.0
  html: ^0.15.4

  flutter_tts: ^3.8.1

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6

  flutter_lints: ^2.0.3

  flutter_launcher_icons: ^0.13.1

  injectable_generator: ^2.4.0

  auto_route_generator: ^7.3.1

  flutter_gen_runner: ^5.3.1

  freezed: ^2.3.2

  json_serializable: ^6.7.1

flutter:

  generate: true

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato_regular.ttf
          style: normal
          weight: 400
        - asset: fonts/lato_bold.ttf
          style: normal
          weight: 700
    - family: FiraSans
      fonts:
        - asset: fonts/fira_sans_italic.ttf
          style: italic
          weight: 400

flutter_gen:
  integrations:
    flutter_svg: true