// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnOO8umvjUcQ0_FkI3OIBKEVLrvvUk-pA',
    appId: '1:736998502997:web:bcc88878af5e19986f9adc',
    messagingSenderId: '736998502997',
    projectId: 'english-words-71def',
    authDomain: 'english-words-71def.firebaseapp.com',
    storageBucket: 'english-words-71def.appspot.com',
    measurementId: 'G-9BWK4CQFS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJ1cRBzq43cEuPpkUyuY1jg4Ziba4A5A',
    appId: '1:736998502997:android:4dea54862a579f0c6f9adc',
    messagingSenderId: '736998502997',
    projectId: 'english-words-71def',
    storageBucket: 'english-words-71def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohLOuKvSmHKUJuILcsRI0g7MKsJ1Khik',
    appId: '1:736998502997:ios:86f1c4d7553865c16f9adc',
    messagingSenderId: '736998502997',
    projectId: 'english-words-71def',
    storageBucket: 'english-words-71def.appspot.com',
    iosClientId: '736998502997-irkgsp4b1kma495sqlt1om14tm1b2jee.apps.googleusercontent.com',
    iosBundleId: 'pl.piotr.englishwords.englishWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohLOuKvSmHKUJuILcsRI0g7MKsJ1Khik',
    appId: '1:736998502997:ios:86f1c4d7553865c16f9adc',
    messagingSenderId: '736998502997',
    projectId: 'english-words-71def',
    storageBucket: 'english-words-71def.appspot.com',
    iosClientId: '736998502997-irkgsp4b1kma495sqlt1om14tm1b2jee.apps.googleusercontent.com',
    iosBundleId: 'pl.piotr.englishwords.englishWords',
  );
}
